package drl.adress

import quick.boot.drools.entity.Address;
import quick.boot.drools.entity.BooleanResult;
import quick.boot.drools.entity.OutputDisplay;

global OutputDisplay showResult;

rule "Postcode 5 numbers"
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : BooleanResult();
    then
        checkResult.setPostCodeResult(true);
        showResult.showText("规则5中打印日志：校验通过!");
end