package drl.ming
import quick.boot.drools.entity.Ming;


// 小明喝汽水问题
// 1元钱一瓶汽水，喝完后两个空瓶换一瓶汽水，问：小明有20元钱，最多可以喝到几瓶汽水？
// 规则1：1元钱一瓶汽水
// 规则2：两个空瓶换一瓶汽水

// 规则1：1元钱一瓶汽水。有钱就买水，空瓶+1，钱-1，喝水+1；
rule "ming-rule1"
    salience 3
    when
        $m:Ming(money > 0);
    then
        System.out.println("有钱即可喝水，钱：" + $m.getMoney());
        $m.setBottle($m.getBottle() + 1);
        $m.setMoney($m.getMoney() - 1);
        $m.setDrink($m.getDrink() + 1);
        update($m)
end

// 规则2：两个空瓶换一瓶汽水。有空瓶就换钱，空瓶-2，钱+1；
rule "ming-rule2"
    salience 2
    when
        $m:Ming(bottle >= 2);
    then
        System.out.println("有瓶子就换钱，瓶子：" + $m.getBottle());
        $m.setBottle($m.getBottle() - 2);
        $m.setMoney($m.getMoney() + 1);
        update($m)
end