server:
  port: 8001

spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    # 开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true

