server:
  port: 8002

spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
    listener:
      simple:
        retry:
          # 是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          enabled: true
          # 最大重试次数
          max-attempts: 5
          # 重试间隔时间（单位毫秒）
          initial-interval: 1000
        # 重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
        default-requeue-rejected: false
        # 手动ack
        acknowledge-mode: manual


